services:
  - type: web
    name: tidescore-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000 --timeout 120
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: tidescore-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
